from abc import ABCMeta, abstractmethod
import datetime
import queue

import numpy as np
import pandas as pd

from event import SignalEvent

class Strategy:
    '''
    Abstract base class for strategy handling objects

    Generate Signal objects for particular symbols
    based on inputs of Bars (OHLCV) generated by
    DataHandler obj

    Works for historic + live data
    '''
    __metaclass__ = ABCMeta

    @abstractmethod
    def calculate_signals(self):
        '''
        Provides the mechanisms to calculate the list of signals
        '''
        raise NotImplementedError("Should implement calculate_signals()")
    